server:
  port: 8002
spring:
  application:
  name: spring-cloud-config-server
  datasource:
    url: jdbc:mysql://101.37.169.26:3305/bt_test?serverTimezone=CST&useUnicode=true&characterEncoding=UTF-8
    username: hzcs_admin
    password: hzcs_admin_1
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    maxActive: 150
    initialSize: 20
    minIdle: 2
    maxIdle: 60
    testWhileIdle: true
    validationQuery: select 1 from dual